apiVersion: apps/v1
kind: Deployment

metadata:
  name: terraform-gke

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: terraform-gke

  template:
    metadata:
      labels:
        app: terraform-gke

    spec:
      containers:
      - name: terraform-gke

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:
        - containerPort: {{ .Values.containerPort }}
