apiVersion: v1
kind: Service

metadata:
  name: terraform-gke-service

spec:
  type: {{ .Values.service.type }}

  selector:
    app: terraform-gke

  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.containerPort }}
